export default [{
  $cnl: 'C9574771',
  $created_at: '2021-11-30T11:01:17.567Z',
  $created_by: 10196,
  $deleted: false,
  $domain: 'Collection',
  $id: 9730422,
  $parent: 21169,
  active: true,
  adeo_collection_all_activities_integer: 104,
  adeo_collection_attr_after_sales_service_current_enum: 'ADEO_YesNo:',
  adeo_collection_attr_after_sales_service_target_enum: 'ADEO_YesNo:',
  adeo_collection_attr_category_manager_cm_reflist: [],
  adeo_collection_attr_cp10_bricocenter_ref: 1,
  adeo_collection_attr_cp10_bricocenter_secondary_ref: 9730427,
  adeo_collection_attr_cp10_bricocenter_stringmap: {
    C9575417: ''
  },
  adeo_collection_attr_cp11_weldom_int_ref: 1,
  adeo_collection_attr_cp11_weldom_int_stringmap: { },
  adeo_collection_attr_cp12_aki_es_ref: 1,
  adeo_collection_attr_cp12_aki_es_stringmap: { },
  adeo_collection_attr_cp13_aki_pt_ref: 1,
  adeo_collection_attr_cp13_aki_pt_stringmap: { },
  adeo_collection_attr_cp14_bricoman_fr_ref: 1,
  adeo_collection_attr_cp14_bricoman_fr_stringmap: { },
  adeo_collection_attr_cp17_weldom_ser_ref: 1,
  adeo_collection_attr_cp17_weldom_ser_secondary_ref: 9730450,
  adeo_collection_attr_cp17_weldom_ser_stringmap: {
    C9575405: ''
  },
  adeo_collection_attr_cp18_bricomart_ref: 1,
  adeo_collection_attr_cp18_bricomart_stringmap: { },
  adeo_collection_attr_cp19_lmgrcy_ref: 1,
  adeo_collection_attr_cp19_lmgrcy_secondary_ref: 9730470,
  adeo_collection_attr_cp19_lmgrcy_stringmap: {
    C9575437: ''
  },
  adeo_collection_attr_cp1_lmfr_ref: 1,
  adeo_collection_attr_cp1_lmfr_secondary_ref: 9730461,
  adeo_collection_attr_cp1_lmfr_stringmap: {
    C9575401: ''
  },
  adeo_collection_attr_cp20_bricoman_pl_ref: 1,
  adeo_collection_attr_cp20_bricoman_pl_stringmap: { },
  adeo_collection_attr_cp21_zodio_fr_ref: 1,
  adeo_collection_attr_cp21_zodio_fr_stringmap: { },
  adeo_collection_attr_cp22_bricoman_it_ref: 1,
  adeo_collection_attr_cp22_bricoman_it_stringmap: { },
  adeo_collection_attr_cp23_lmua_ref: 1,
  adeo_collection_attr_cp23_lmua_secondary_ref: 9730462,
  adeo_collection_attr_cp23_lmua_stringmap: {
    C9575445: ''
  },
  adeo_collection_attr_cp26_lmro_ref: 1,
  adeo_collection_attr_cp26_lmro_secondary_ref: 9730451,
  adeo_collection_attr_cp26_lmro_stringmap: {
    C9575449: ''
  },
  adeo_collection_attr_cp2_lmes_ref: 1,
  adeo_collection_attr_cp2_lmes_secondary_ref: 9730446,
  adeo_collection_attr_cp2_lmes_stringmap: {
    C9575409: ''
  },
  adeo_collection_attr_cp38_zodio_br_ref: 1,
  adeo_collection_attr_cp38_zodio_br_stringmap: { },
  adeo_collection_attr_cp3_lmpt_ref: 1,
  adeo_collection_attr_cp3_lmpt_secondary_ref: 9730477,
  adeo_collection_attr_cp3_lmpt_stringmap: {
    C9575433: ''
  },
  adeo_collection_attr_cp53_lmza_ref: 1,
  adeo_collection_attr_cp53_lmza_stringmap: { },
  adeo_collection_attr_cp56_alice_delice_ref: 1,
  adeo_collection_attr_cp56_alice_delice_stringmap: { },
  adeo_collection_attr_cp5_lmit_ref: 1,
  adeo_collection_attr_cp5_lmit_secondary_ref: 9730434,
  adeo_collection_attr_cp5_lmit_stringmap: {
    C9575413: ''
  },
  adeo_collection_attr_cp6_lmpl_ref: 1,
  adeo_collection_attr_cp6_lmpl_secondary_ref: 9730492,
  adeo_collection_attr_cp6_lmpl_stringmap: {
    C9575425: ''
  },
  adeo_collection_attr_cp7_lmbr_ref: 1,
  adeo_collection_attr_cp7_lmbr_stringmap: { },
  adeo_collection_attr_cp9_lmru_ref: 1,
  adeo_collection_attr_cp9_lmru_stringmap: { },
  adeo_collection_attr_customer_feedback_current_double: 0.0,
  adeo_collection_attr_customer_feedback_target_double: 0.0,
  adeo_collection_attr_department01_enum: 'ADEO_Department:04',
  adeo_collection_attr_department02_enum: 'ADEO_Department:04',
  adeo_collection_attr_department03_enum: 'ADEO_Department:04',
  adeo_collection_attr_department04_enum: 'ADEO_Department:04',
  adeo_collection_attr_department05_enum: 'ADEO_Department:04',
  adeo_collection_attr_dev_type_co_development_double: 0.0,
  adeo_collection_attr_dev_type_conception_double: 0.0,
  adeo_collection_attr_dev_type_selection_double: 0.0,
  adeo_collection_attr_factor_of_success_string: '',
  adeo_collection_attr_family01_enum: [],
  adeo_collection_attr_family02_enum: [],
  adeo_collection_attr_family03_enum: [],
  adeo_collection_attr_family04_enum: [],
  adeo_collection_attr_family05_enum: [],
  adeo_collection_attr_first_inhabitant_availability_time: '1970-01-01T00:00:00Z',
  adeo_collection_attr_go_for_analysis_boo: false,
  adeo_collection_attr_go_for_analysis_change_boo: false,
  adeo_collection_attr_go_for_build_boo: false,
  adeo_collection_attr_go_for_build_change_boo: false,
  adeo_collection_attr_go_for_design_boo: false,
  adeo_collection_attr_go_for_design_change_boo: false,
  adeo_collection_attr_go_for_development_boo: false,
  adeo_collection_attr_go_for_development_change_boo: false,
  adeo_collection_attr_go_for_ending_boo: false,
  adeo_collection_attr_go_for_ending_change_boo: false,
  adeo_collection_attr_go_for_indus_boo: false,
  adeo_collection_attr_go_for_indus_change_boo: false,
  adeo_collection_attr_go_for_mass_prod_boo: false,
  adeo_collection_attr_go_for_mass_prod_change_boo: false,
  adeo_collection_attr_go_for_project_boo: false,
  adeo_collection_attr_go_for_project_change_boo: false,
  adeo_collection_attr_go_for_purchasing_boo: false,
  adeo_collection_attr_go_for_purchasing_change_boo: false,
  adeo_collection_attr_intellectual_property_bool: false,
  adeo_collection_attr_list_bu_with_cp_stringmap: {
    C9575401: '',
    C9575405: '',
    C9575409: '',
    C9575413: '',
    C9575417: '',
    C9575425: '',
    C9575433: '',
    C9575437: '',
    C9575445: '',
    C9575449: ''
  },
  adeo_collection_attr_madeto_last_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_notification_list_complete_boolean: false,
  adeo_collection_attr_pitch_string: '\n\n\n\n\n',
  adeo_collection_attr_project_code_string: '2022R04S12',
  adeo_collection_attr_project_life_time_double: 0.0,
  adeo_collection_attr_project_name_string: 'SET OF MIXED TOOLS',
  adeo_collection_attr_project_qualification_enum: 'ADEO_ProjectQualification:',
  adeo_collection_attr_project_scope_enum: 'ADEO_ProjectScope:',
  adeo_collection_attr_responsible_prod_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_return_rate_current_double: 0.0,
  adeo_collection_attr_return_rate_target_double: 0.0,
  adeo_collection_attr_safe_for_planet_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_sub_department01_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department02_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department03_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department04_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department05_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sustainable_and_recycle_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_sustainable_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_team_bu_co_leader1_ref: 1,
  adeo_collection_attr_team_bu_co_leader2_ref: 1,
  adeo_collection_attr_team_bucp_leader_bu_enum: 'ADEO_BusinessUnit:',
  adeo_collection_attr_team_bucp_leader_ref: 1,
  adeo_collection_attr_team_industry_conception_engineer_ref: [],
  adeo_collection_attr_team_industry_design_ref: [],
  adeo_collection_attr_team_industry_il_ref: [1819666],
  adeo_collection_attr_team_industry_industrial_buyer_ref: [],
  adeo_collection_attr_team_industry_industrial_drawer_ref: [],
  adeo_collection_attr_team_industry_pack_ref: [],
  adeo_collection_attr_team_product_business_serial_life_manager_ref: [],
  adeo_collection_attr_team_product_ccp_ref: [],
  adeo_collection_attr_team_product_cl_ref: [10344],
  adeo_collection_attr_team_product_dl_ref: [208229],
  adeo_collection_attr_team_product_lui_ref: [],
  adeo_collection_attr_team_product_ml_ref: 240771,
  adeo_collection_attr_team_product_notice_manager_ref: [],
  adeo_collection_attr_team_product_pcm_ref: [7355063],
  adeo_collection_attr_team_product_rcp_ref: [7734197],
  adeo_collection_attr_team_purchase_industrialization_manager_ref: [],
  adeo_collection_attr_team_purchase_sourcing_manager_reflist: [],
  adeo_collection_attr_team_purchase_supply_pl_ref: [10346],
  adeo_collection_attr_team_purchase_supply_raf_ref: [],
  adeo_collection_attr_team_purchase_supply_sco_ref: [8345801],
  adeo_collection_attr_team_quality_continuous_improvement_ref: [],
  adeo_collection_attr_team_quality_pqm_ref: [],
  adeo_collection_attr_value_creation_commercialization_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_offer_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_purchasing_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_quality_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_re_conception_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_supply_chain_enum: 'ADEO_Value1to5:',
  adeo_collection_category2_code_string: 'R04',
  adeo_collection_cnt_stylei1_int: 0,
  adeo_collection_cnt_stylei2_int: 0,
  adeo_collection_collection_url_string: 'C9574771',
  adeo_collection_dataware_family_update_boolean: false,
  adeo_collection_dataware_update_boolean: false,
  adeo_collection_freeze_matrix_id_boolean: true,
  adeo_collection_group_number_enum: 'ADEO_ListOfNumber:',
  adeo_collection_initial_project_code_string: '2019R04P10',
  adeo_collection_master_calendar_link_ref: 6409783,
  adeo_collection_merch_collection_version_ref: 9730500,
  adeo_collection_nb_of_calendar_integer: 1,
  adeo_collection_parent_group_ref: 9730422,
  adeo_collection_parent_season_code_string: '2022',
  adeo_collection_principal_brand_ref: 1,
  adeo_collection_project_code_string: '2022R04S12',
  adeo_collection_project_group_boolean: false,
  adeo_collection_project_name_string: 'SET OF MIXED TOOLS',
  adeo_collection_project_status_date_date: '1970-01-01T00:00:00Z',
  adeo_collection_project_status_enum: 'ADEO_ProjectStatus:0',
  adeo_collection_project_type_enum: 'ADEO_ProcessType:020',
  adeo_collection_scope_enum: 'ADEO_RegionalScope:',
  adeo_collection_step_update_boolean: false,
  adeo_collection_visible_docs_reflist: [],
  adeo_list_of_models: [],
  adeo_purchasing_expected_cbd_level: 'ADEO_CBDLevel:',
  adeo_purchasing_expected_indus_level: 'ADEO_IndustralizationLevel:',
  adeo_purchasing_nb_products_for_tender: 0,
  adeo_purchasing_nb_tender_round: 'ADEO_NbTenderRound:',
  adeo_purchasing_to_for_tender: 0.0,
  calendar: [9732712],
  calendar_level: 213,
  category1: 21159,
  category2: 21169,
  cnt_colorway: 0,
  cnt_documents: 0,
  cnt_style: 5,
  code: '12',
  comments: [],
  contained_by: [],
  crew: 1,
  crew_type: 49,
  data_sheets: [],
  defaults: 1,
  description: '',
  documents: [],
  expr: 71,
  hierarchy: [9731056, 9731039, 9731048, 9731057, 9731040],
  images: {
    1: 9730607
  },
  issue_category1: 21159,
  issue_category2: 21169,
  issue_collection: 9730422,
  issue_product: 1,
  issue_season: 20981,
  issues: [],
  master_container: 20981,
  material_schedule: 1,
  material_schedule_allowed: true,
  material_schedules: [],
  matrix: 9730423,
  modified_at: '2021-12-02T09:02:41.488Z',
  modified_by: 10344,
  node_name: '2022R04S12 - SET OF MIXED TOOLS',
  parent_season: 20981,
  recent_comments: [],
  referenced_documents: [],
  select_sets: [],
  shared_spec_sections: [31668],
  wbs: 1,
  wbs_enabled: false,
  wbs_reports_enabled: true,
  wbs_request: 1
}, {
  $cnl: 'C9290836',
  $created_at: '2021-11-29T16:49:56.303Z',
  $created_by: 10196,
  $deleted: false,
  $domain: 'Collection',
  $id: 9441335,
  $parent: 6547621,
  active: true,
  adeo_collection_all_activities_integer: 0,
  adeo_collection_attr_after_sales_service_current_enum: 'ADEO_YesNo:',
  adeo_collection_attr_after_sales_service_target_enum: 'ADEO_YesNo:',
  adeo_collection_attr_category_manager_cm_reflist: [],
  adeo_collection_attr_cp10_bricocenter_ref: 1,
  adeo_collection_attr_cp10_bricocenter_stringmap: { },
  adeo_collection_attr_cp11_weldom_int_ref: 1,
  adeo_collection_attr_cp11_weldom_int_stringmap: { },
  adeo_collection_attr_cp12_aki_es_ref: 1,
  adeo_collection_attr_cp12_aki_es_stringmap: { },
  adeo_collection_attr_cp13_aki_pt_ref: 1,
  adeo_collection_attr_cp13_aki_pt_stringmap: { },
  adeo_collection_attr_cp14_bricoman_fr_ref: 1,
  adeo_collection_attr_cp14_bricoman_fr_stringmap: { },
  adeo_collection_attr_cp17_weldom_ser_ref: 1,
  adeo_collection_attr_cp17_weldom_ser_stringmap: { },
  adeo_collection_attr_cp18_bricomart_ref: 1,
  adeo_collection_attr_cp18_bricomart_stringmap: { },
  adeo_collection_attr_cp19_lmgrcy_ref: 1,
  adeo_collection_attr_cp19_lmgrcy_stringmap: { },
  adeo_collection_attr_cp1_lmfr_ref: 1,
  adeo_collection_attr_cp1_lmfr_stringmap: { },
  adeo_collection_attr_cp20_bricoman_pl_ref: 1,
  adeo_collection_attr_cp20_bricoman_pl_stringmap: { },
  adeo_collection_attr_cp21_zodio_fr_ref: 1,
  adeo_collection_attr_cp21_zodio_fr_stringmap: { },
  adeo_collection_attr_cp22_bricoman_it_ref: 1,
  adeo_collection_attr_cp22_bricoman_it_stringmap: { },
  adeo_collection_attr_cp23_lmua_ref: 1,
  adeo_collection_attr_cp23_lmua_stringmap: { },
  adeo_collection_attr_cp26_lmro_ref: 1,
  adeo_collection_attr_cp26_lmro_stringmap: { },
  adeo_collection_attr_cp2_lmes_ref: 1,
  adeo_collection_attr_cp2_lmes_stringmap: { },
  adeo_collection_attr_cp38_zodio_br_ref: 1,
  adeo_collection_attr_cp38_zodio_br_stringmap: { },
  adeo_collection_attr_cp3_lmpt_ref: 1,
  adeo_collection_attr_cp3_lmpt_stringmap: { },
  adeo_collection_attr_cp53_lmza_ref: 1,
  adeo_collection_attr_cp53_lmza_stringmap: { },
  adeo_collection_attr_cp56_alice_delice_ref: 1,
  adeo_collection_attr_cp56_alice_delice_stringmap: { },
  adeo_collection_attr_cp5_lmit_ref: 1,
  adeo_collection_attr_cp5_lmit_stringmap: { },
  adeo_collection_attr_cp6_lmpl_ref: 1,
  adeo_collection_attr_cp6_lmpl_stringmap: { },
  adeo_collection_attr_cp7_lmbr_ref: 1,
  adeo_collection_attr_cp7_lmbr_stringmap: { },
  adeo_collection_attr_cp9_lmru_ref: 1,
  adeo_collection_attr_cp9_lmru_stringmap: { },
  adeo_collection_attr_customer_feedback_current_double: 0.0,
  adeo_collection_attr_customer_feedback_target_double: 0.0,
  adeo_collection_attr_department01_enum: 'ADEO_Department:04',
  adeo_collection_attr_department02_enum: 'ADEO_Department:04',
  adeo_collection_attr_department03_enum: 'ADEO_Department:04',
  adeo_collection_attr_department04_enum: 'ADEO_Department:04',
  adeo_collection_attr_department05_enum: 'ADEO_Department:04',
  adeo_collection_attr_dev_type_co_development_double: 0.0,
  adeo_collection_attr_dev_type_conception_double: 0.0,
  adeo_collection_attr_dev_type_selection_double: 0.0,
  adeo_collection_attr_factor_of_success_string: '',
  adeo_collection_attr_family01_enum: [],
  adeo_collection_attr_family02_enum: [],
  adeo_collection_attr_family03_enum: [],
  adeo_collection_attr_family04_enum: [],
  adeo_collection_attr_family05_enum: [],
  adeo_collection_attr_first_inhabitant_availability_time: '1970-01-01T00:00:00Z',
  adeo_collection_attr_go_for_analysis_boo: false,
  adeo_collection_attr_go_for_analysis_change_boo: false,
  adeo_collection_attr_go_for_build_boo: false,
  adeo_collection_attr_go_for_build_change_boo: false,
  adeo_collection_attr_go_for_design_boo: false,
  adeo_collection_attr_go_for_design_change_boo: false,
  adeo_collection_attr_go_for_development_boo: false,
  adeo_collection_attr_go_for_development_change_boo: false,
  adeo_collection_attr_go_for_ending_boo: false,
  adeo_collection_attr_go_for_ending_change_boo: false,
  adeo_collection_attr_go_for_indus_boo: false,
  adeo_collection_attr_go_for_indus_change_boo: false,
  adeo_collection_attr_go_for_mass_prod_boo: false,
  adeo_collection_attr_go_for_mass_prod_change_boo: false,
  adeo_collection_attr_go_for_project_boo: false,
  adeo_collection_attr_go_for_project_change_boo: false,
  adeo_collection_attr_go_for_purchasing_boo: false,
  adeo_collection_attr_go_for_purchasing_change_boo: false,
  adeo_collection_attr_intellectual_property_bool: false,
  adeo_collection_attr_list_bu_with_cp_stringmap: { },
  adeo_collection_attr_madeto_last_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_notification_list_complete_boolean: false,
  adeo_collection_attr_pitch_string: '\n\n\n\n\n',
  adeo_collection_attr_project_code_string: '2024R04P02',
  adeo_collection_attr_project_life_time_double: 0.0,
  adeo_collection_attr_project_name_string: 'HAND AND HEAD PROTECTION',
  adeo_collection_attr_project_qualification_enum: 'ADEO_ProjectQualification:',
  adeo_collection_attr_project_scope_enum: 'ADEO_ProjectScope:',
  adeo_collection_attr_responsible_prod_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_return_rate_current_double: 0.0,
  adeo_collection_attr_return_rate_target_double: 0.0,
  adeo_collection_attr_safe_for_planet_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_sub_department01_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department02_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department03_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department04_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sub_department05_enum: 'ADEO_SubDepartment:',
  adeo_collection_attr_sustainable_and_recycle_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_sustainable_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_team_bu_co_leader1_ref: 1,
  adeo_collection_attr_team_bu_co_leader2_ref: 1,
  adeo_collection_attr_team_bucp_leader_bu_enum: 'ADEO_BusinessUnit:',
  adeo_collection_attr_team_bucp_leader_ref: 1,
  adeo_collection_attr_team_industry_conception_engineer_ref: [],
  adeo_collection_attr_team_industry_design_ref: [],
  adeo_collection_attr_team_industry_il_ref: [],
  adeo_collection_attr_team_industry_industrial_buyer_ref: [],
  adeo_collection_attr_team_industry_industrial_drawer_ref: [],
  adeo_collection_attr_team_industry_pack_ref: [],
  adeo_collection_attr_team_product_business_serial_life_manager_ref: [],
  adeo_collection_attr_team_product_ccp_ref: [],
  adeo_collection_attr_team_product_cl_ref: [],
  adeo_collection_attr_team_product_dl_ref: [],
  adeo_collection_attr_team_product_lui_ref: [],
  adeo_collection_attr_team_product_ml_ref: 1,
  adeo_collection_attr_team_product_notice_manager_ref: [],
  adeo_collection_attr_team_product_pcm_ref: [],
  adeo_collection_attr_team_product_rcp_ref: [],
  adeo_collection_attr_team_purchase_industrialization_manager_ref: [],
  adeo_collection_attr_team_purchase_sourcing_manager_reflist: [],
  adeo_collection_attr_team_purchase_supply_pl_ref: [],
  adeo_collection_attr_team_purchase_supply_raf_ref: [],
  adeo_collection_attr_team_purchase_supply_sco_ref: [],
  adeo_collection_attr_team_quality_continuous_improvement_ref: [],
  adeo_collection_attr_team_quality_pqm_ref: [],
  adeo_collection_attr_value_creation_commercialization_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_offer_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_purchasing_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_quality_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_re_conception_enum: 'ADEO_Value1to5:',
  adeo_collection_attr_value_creation_supply_chain_enum: 'ADEO_Value1to5:',
  adeo_collection_category2_code_string: 'R04',
  adeo_collection_cnt_stylei1_int: 0,
  adeo_collection_cnt_stylei2_int: 0,
  adeo_collection_collection_url_string: 'C9290836',
  adeo_collection_dataware_family_update_boolean: false,
  adeo_collection_dataware_update_boolean: false,
  adeo_collection_freeze_matrix_id_boolean: false,
  adeo_collection_group_number_enum: 'ADEO_ListOfNumber:',
  adeo_collection_initial_project_code_string: '2024R04P02',
  adeo_collection_merch_collection_version_ref: 9441409,
  adeo_collection_nb_of_calendar_integer: 0,
  adeo_collection_parent_group_ref: 9441335,
  adeo_collection_parent_season_code_string: '2024',
  adeo_collection_principal_brand_ref: 1,
  adeo_collection_project_code_string: '2024R04P02',
  adeo_collection_project_group_boolean: true,
  adeo_collection_project_name_string: 'HAND AND HEAD PROTECTION',
  adeo_collection_project_status_date_date: '1970-01-01T00:00:00Z',
  adeo_collection_project_status_enum: 'ADEO_ProjectStatus:',
  adeo_collection_project_type_enum: 'ADEO_ProcessType:010',
  adeo_collection_scope_enum: 'ADEO_RegionalScope:',
  adeo_collection_step_update_boolean: false,
  adeo_collection_visible_docs_reflist: [],
  adeo_list_of_models: [],
  adeo_purchasing_expected_cbd_level: 'ADEO_CBDLevel:',
  adeo_purchasing_expected_indus_level: 'ADEO_IndustralizationLevel:',
  adeo_purchasing_nb_products_for_tender: 0,
  adeo_purchasing_nb_tender_round: 'ADEO_NbTenderRound:',
  adeo_purchasing_to_for_tender: 0.0,
  calendar: [],
  calendar_level: 213,
  category1: 6547603,
  category2: 6547621,
  cnt_colorway: 0,
  cnt_documents: 0,
  cnt_style: 0,
  code: '02',
  comments: [],
  contained_by: [],
  crew: 1,
  crew_type: 49,
  data_sheets: [],
  defaults: 1,
  description: '',
  documents: [],
  expr: 71,
  hierarchy: [],
  images: { },
  issue_category1: 6547603,
  issue_category2: 6547621,
  issue_collection: 9441335,
  issue_product: 1,
  issue_season: 6547531,
  issues: [],
  master_container: 6547531,
  material_schedule: 1,
  material_schedule_allowed: true,
  material_schedules: [],
  matrix: 9441336,
  modified_at: '2021-11-29T16:50:44.521Z',
  modified_by: 10196,
  node_name: '2024R04P02 - HAND AND HEAD PROTECTION',
  parent_season: 6547531,
  recent_comments: [],
  referenced_documents: [],
  select_sets: [],
  shared_spec_sections: [],
  wbs: 1,
  wbs_enabled: false,
  wbs_reports_enabled: true,
  wbs_request: 1
}]
