export default {
  specificationItemDefinition: 'SpecificationItemDefinition',
  specificationSectionItem: 'SpecificationSectionItem',
  specificationDataSheet: 'SpecificationDataSheet',
  classifier: 'Classifier',
  specificationSection: 'SpecificationSection',
  style: 'Style',
  productSymbol: 'ProductSymbol',
  specificationDataSheetRevision: 'SpecificationDataSheetRevision',
  specificationDataSheetItem: 'SpecificationDataSheetItem',
  collection: 'Collection',
  merchCollectionVersion: 'MerchCollectionVersion',
  merchSecondaryVersion: 'MerchSecondaryVersion',
  merchProductVersion: 'MerchProductVersion',
  merchSecondaryPlan: 'MerchSecondaryPlan',
  specSection: 'SpecificationSection',
  user: 'User',
  role: 'Role',
  activity: 'Activity',
  calendar: 'Calendar',
  productDevelopment: 'ProductDevelopment'
}
