export default (inputField) => {
  switch (inputField) {
    case 'ADEO_SubDepartment:0105': return '05 - CONSTRUCTION EQUIPMENT'
    case 'ADEO_SubDepartment:0110': return '10 - POWDERS, SANDS, AGGREGATES'
    case 'ADEO_SubDepartment:0115': return '15 - CONSTRUCTION ELEMENTS AND TIMBER'
    case 'ADEO_SubDepartment:0120': return '20 - STORM AND FOUL WATER DRAINAGE'
    case 'ADEO_SubDepartment:0125': return '25 - ROOFING AND COVERINGS'
    case 'ADEO_SubDepartment:0130': return '30 - HOUSE INSULATION'
    case 'ADEO_SubDepartment:0135': return '35 - PARTITIONS AND INTERNAL CEILINGS'
    case 'ADEO_SubDepartment:0138': return '38 - GLASS BRICKS'
    case 'ADEO_SubDepartment:0199': return '99 - MATERIALS: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0205': return '05 - WINDOWS , DOORS , OUTDOOR BLINDS AND SHUTTERS'
    case 'ADEO_SubDepartment:0210': return '10 - INTERIOR DOORS AND SEPARATORS'
    case 'ADEO_SubDepartment:0215': return '15 - STAIRCASES, MEZZANINES, BALUSTERS'
    case 'ADEO_SubDepartment:0220': return '20 - GLASS PRODUCTS'
    case 'ADEO_SubDepartment:0225': return '25 - DECORATIVE AND FINISHING WOOD'
    case 'ADEO_SubDepartment:0230': return '30 - WOOD PANELS'
    case 'ADEO_SubDepartment:0235': return '35 - INDIVIDUAL BOARDS'
    case 'ADEO_SubDepartment:0240': return '40 - WALL COVERINGS - WOOD AND PVC'
    case 'ADEO_SubDepartment:0299': return '99 - WOOD : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0305': return '05 - POWER DISTRIBUTION PROTECTION'
    case 'ADEO_SubDepartment:0308': return '08 - ELECTRICAL SWITCHES AND SOCKETS'
    case 'ADEO_SubDepartment:0310': return '10 - ELECTRICAL CABLE, SHEATING AND CONNECTIONS ACCESSORIES'
    case 'ADEO_SubDepartment:0312': return '12 - ELECTRICAL EQUIPMENT'
    case 'ADEO_SubDepartment:0315': return '15 - WATER, GAS, OIL SUPPLY AND FIXING'
    case 'ADEO_SubDepartment:0318': return '18 - SECURITY AND ACCES CONTROL'
    case 'ADEO_SubDepartment:0320': return '20 - RECEPTION, TRANSMISSION AND DISTRIBUTION OF A SIGNAL'
    case 'ADEO_SubDepartment:0325': return '25 - WATER TREATMENT'
    case 'ADEO_SubDepartment:0330': return '30 - WC EQUIPMENT'
    case 'ADEO_SubDepartment:0345': return '45 - AUTONOMIOUS ENERGY AND RENEWABLE ENERGY'
    case 'ADEO_SubDepartment:0350': return '50 - WATER EVACUATION / DRAINAGE'
    case 'ADEO_SubDepartment:0399': return '99 - ELECTRICITY PLUMBING : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0405': return '05 - STANDARD HAND TOOLS'
    case 'ADEO_SubDepartment:0410': return '10 - SPECIALIST HAND TOOLS'
    case 'ADEO_SubDepartment:0415': return '15 - PORTABLE POWER TOOLS'
    case 'ADEO_SubDepartment:0420': return '20 - WORKSHOP OR CONSTRUCTION SITE MACHINES AND EQUIPEMENT'
    case 'ADEO_SubDepartment:0430': return '30 - CONSUMABLES AND ACCESSORIES'
    case 'ADEO_SubDepartment:0435': return '35 - TOOL AND FIXING STORAGE'
    case 'ADEO_SubDepartment:0440': return '40 - WORKER PROTECTION'
    case 'ADEO_SubDepartment:0499': return '99 - TOOLS: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0505': return '05 - CARPET'
    case 'ADEO_SubDepartment:0510': return '10 - PVC FLOORING ROLLS'
    case 'ADEO_SubDepartment:0515': return '15 - PVC FLOORING PLANKS AND TILES'
    case 'ADEO_SubDepartment:0520': return '20 - FLOORING FINISHING'
    case 'ADEO_SubDepartment:0525': return '25 - FLOORING PREPARATION'
    case 'ADEO_SubDepartment:0535': return '35 - WOOD AND ENGINEERED FLOORING'
    case 'ADEO_SubDepartment:0540': return '40 - LAMINATE FLOORING'
    case 'ADEO_SubDepartment:0599': return '99 - WOODEN FLOOR CARPET FLORING : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0605': return '05 - WALL TILING'
    case 'ADEO_SubDepartment:0610': return '10 - TILING: BORDER TILES AND TILING TRIMS'
    case 'ADEO_SubDepartment:0615': return '15 - FLOOR TILING: ENAMELLED AND NON ENAMELLED'
    case 'ADEO_SubDepartment:0620': return '20 - MOSAICS, PEBBLES'
    case 'ADEO_SubDepartment:0625': return '25 - TILING: LAYING, CARE AND FINISHING PRODUCTS'
    case 'ADEO_SubDepartment:0655': return '55 - CLADDINGS'
    case 'ADEO_SubDepartment:0699': return '99 - TILING: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0705': return '05 - WAHSBASINS, BASINS'
    case 'ADEO_SubDepartment:0715': return '15 - SHOWER ENCLOSURES & SHOWER TRAYS'
    case 'ADEO_SubDepartment:0720': return '20 - BATHROOM AND WC ACCESSORIES AND BATHMATS'
    case 'ADEO_SubDepartment:0730': return '30 - BATHROOM FURNITURE, MIRRORS AND BATHROOM CABINET'
    case 'ADEO_SubDepartment:0735': return '35 - TOILET, BIDET, FRAME'
    case 'ADEO_SubDepartment:0738': return '38 - BATHTUBS & BATHSCREENS, WELLNESS'
    case 'ADEO_SubDepartment:0740': return '40 - BATHROOM FAUCETS AND SPARE PARTS'
    case 'ADEO_SubDepartment:0745': return '45 - HYDROTHERAPY'
    case 'ADEO_SubDepartment:0799': return '99 - BATHROOM: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0830': return '30 - ELECTRIC HEATING'
    case 'ADEO_SubDepartment:0835': return '35 - WATER HEATERS'
    case 'ADEO_SubDepartment:0840': return '40 - BOILERS AND ACCESSORIES'
    case 'ADEO_SubDepartment:0842': return '42 - Fireplaces, Fireboxes, accessories and maintenance products'
    case 'ADEO_SubDepartment:0845': return '45 - RADIATORS AND ACCESSORIES'
    case 'ADEO_SubDepartment:0850': return '50 - FUEL MOBILE HEATING'
    case 'ADEO_SubDepartment:0855': return '55 - Air and smoke conducts products and accessories'
    case 'ADEO_SubDepartment:0860': return '60 - AIR CONDITIONING, VENTILATION'
    case 'ADEO_SubDepartment:0862': return '62 - AIR TREATMENT'
    case 'ADEO_SubDepartment:0865': return '65 - RENEWABLE ENERGIES FOR INSTALLATION'
    case 'ADEO_SubDepartment:0870': return '70 - Aerothermal , geothermal and heating pumps'
    case 'ADEO_SubDepartment:0875': return '75 - Temperature regulation'
    case 'ADEO_SubDepartment:0899': return '99 - COMFORT : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:0902': return '02 - SEEDS AND BULBS'
    case 'ADEO_SubDepartment:0905': return '05 - MISCELLANEOUS PLANTS'
    case 'ADEO_SubDepartment:0910': return '10 - LAND TOOLS AND MAINTENANCE'
    case 'ADEO_SubDepartment:0915': return '15 - Crop and plant cultivation and protection'
    case 'ADEO_SubDepartment:0920': return '20 - GARDEN CONTAINERS AND DECORATION'
    case 'ADEO_SubDepartment:0925': return '25 - CROP FERTILIZERS AND TREATMENT'
    case 'ADEO_SubDepartment:0930': return '30 - Irrigation and pumps'
    case 'ADEO_SubDepartment:0935': return '35 - MOTORIZED GARDEN EQUIPMENT'
    case 'ADEO_SubDepartment:0938': return '38 - HIGH PRESSURE CLEANERS'
    case 'ADEO_SubDepartment:0940': return '40 - GATES, OCCULTATION AND EXTERIOR DELIMITATION'
    case 'ADEO_SubDepartment:0942': return '42 - OUTDOOR FLORING'
    case 'ADEO_SubDepartment:0945': return '45 - LANDSCAPING'
    case 'ADEO_SubDepartment:0948': return '48 - GARDEN SHELTERS AND STORAGE'
    case 'ADEO_SubDepartment:0950': return '50 - GARDEN FURNITURE AND CHILDREN\'S GAMES'
    case 'ADEO_SubDepartment:0952': return '52 - BARBECUES'
    case 'ADEO_SubDepartment:0955': return '55 - SWIMMING POOLS'
    case 'ADEO_SubDepartment:0960': return '60 - CHRISTMAS DECORATIONS'
    case 'ADEO_SubDepartment:0999': return '99 - GARDEN : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1005': return '05 - Secure goods and people'
    case 'ADEO_SubDepartment:1010': return '10 - To create something'
    case 'ADEO_SubDepartment:1015': return '15 - To repair and equip a door or a window'
    case 'ADEO_SubDepartment:1020': return '20 - To repair and equip a furniture'
    case 'ADEO_SubDepartment:1025': return '25 - To fix and fit together'
    case 'ADEO_SubDepartment:1030': return '30 - Equipment'
    case 'ADEO_SubDepartment:1099': return '99 - HARDWARE : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1105': return '05 - FINISHING PAINT'
    case 'ADEO_SubDepartment:1110': return '10 - FACADES AND ROOFS'
    case 'ADEO_SubDepartment:1115': return '15 - PAINTING TOOLS AND ACCESSORIES'
    case 'ADEO_SubDepartment:1120': return '20 - EXTERIOR FURNITURE AND OBJECTS'
    case 'ADEO_SubDepartment:1122': return '22 - TINTING SYSTEM'
    case 'ADEO_SubDepartment:1125': return '25 - MAINTAIN TOOLS'
    case 'ADEO_SubDepartment:1130': return '30 - GLUES AND SEALANTS'
    case 'ADEO_SubDepartment:1132': return '32 - WHITE PAINTS'
    case 'ADEO_SubDepartment:1135': return '35 - PREPARATION'
    case 'ADEO_SubDepartment:1140': return '40 - HOME MAINTENANCE'
    case 'ADEO_SubDepartment:1145': return '45 - COLOURED AND EFFECTS PAINTS'
    case 'ADEO_SubDepartment:1150': return '50 - FLOOR PAINTS AND PRODUCTS'
    case 'ADEO_SubDepartment:1155': return '55 - SPRAYS'
    case 'ADEO_SubDepartment:1160': return '60 - MAINTAIN PRODUCTS'
    case 'ADEO_SubDepartment:1199': return '99 - PAINT: CODE: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1205': return '05 - WALLPAPER AND WALL COVERINGS'
    case 'ADEO_SubDepartment:1210': return '10 - TEXTILE'
    case 'ADEO_SubDepartment:1215': return '15 - DECORATIVE RUGS'
    case 'ADEO_SubDepartment:1218': return '18 - FUNCTIONAL RUGS'
    case 'ADEO_SubDepartment:1220': return '20 - CURTAIN POLES, RAILS AND CABLES'
    case 'ADEO_SubDepartment:1225': return '25 - INTERIOR BLINDS AND PORTIERES'
    case 'ADEO_SubDepartment:1230': return '30 - CEILING DECORATION'
    case 'ADEO_SubDepartment:1235': return '35 - FRAMING'
    case 'ADEO_SubDepartment:1290': return '90 - ADHESIVES IN ROLLS AND OILCLOTHES'
    case 'ADEO_SubDepartment:1295': return '95 - DECORATIVE ADHESIVES'
    case 'ADEO_SubDepartment:1299': return '99 - DECORATION: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1302': return '02 - ELECTRIC BULBS'
    case 'ADEO_SubDepartment:1305': return '05 - LIGHTING CHANDELIERS AND PENDANTS'
    case 'ADEO_SubDepartment:1310': return '10 - CEILING FANS'
    case 'ADEO_SubDepartment:1315': return '15 - WALL AND CEILING LIGHT'
    case 'ADEO_SubDepartment:1318': return '18 - LIGHTING APPLIANCE BY PURPOSE'
    case 'ADEO_SubDepartment:1320': return '20 - TABLE LAMPS, LAMPSHADES'
    case 'ADEO_SubDepartment:1325': return '25 - FLOOR LAMPS'
    case 'ADEO_SubDepartment:1330': return '30 - FIXED SPOTLIGHTS'
    case 'ADEO_SubDepartment:1332': return '32 - RECESS SPOTLIGHTS'
    case 'ADEO_SubDepartment:1335': return '35 - OUTDOOR LIGHTING'
    case 'ADEO_SubDepartment:1340': return '40 - SOLAR LIGHTS'
    case 'ADEO_SubDepartment:1345': return '45 - Connected lighting'
    case 'ADEO_SubDepartment:1350': return '50 - Lighting kids'
    case 'ADEO_SubDepartment:1399': return '99 - LIGHTING: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1405': return '05 - WARDROBE DOORS'
    case 'ADEO_SubDepartment:1410': return '10 - WARDROBE AND LIVING ROOM STORAGE ARTICLES'
    case 'ADEO_SubDepartment:1415': return '15 - FLAT PACK AND MOUNTED FURNITURE'
    case 'ADEO_SubDepartment:1420': return '20 - UTILITY PLASTIC AND WOOD CONTAINERS'
    case 'ADEO_SubDepartment:1422': return '22 - MOVING ITEMS'
    case 'ADEO_SubDepartment:1425': return '25 - UTILITY SHELVES AND CABINETS'
    case 'ADEO_SubDepartment:1435': return '35 - DECORATIVE WALL SHELVES'
    case 'ADEO_SubDepartment:1440': return '40 - UTILITY STORAGE BRACKETS'
    case 'ADEO_SubDepartment:1445': return '45 - MODULAR STORAGE SOLUTIONS FOR LIVING ROOM'
    case 'ADEO_SubDepartment:1499': return '99 - STORAGE : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1505': return '05 - GENERIC SERVICES'
    case 'ADEO_SubDepartment:1508': return '08 - SERVICES RELATED TO PRODUCTS'
    case 'ADEO_SubDepartment:1599': return '99 - COMPLEMENTARY PRODUCTS (HOUSE, GARDEN AND DIY): 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1605': return '05 - CAR ACCESSORIES AND MAINTENANCE'
    case 'ADEO_SubDepartment:1610': return '10 - SPECIALIST LIBRARY'
    case 'ADEO_SubDepartment:1615': return '15 - CREATIVE LEISURE ACTIVITIES'
    case 'ADEO_SubDepartment:1620': return '20 - DOMESTIC LINEN'
    case 'ADEO_SubDepartment:1630': return '30 - TABLE ARTS AND CULINARY ITEMS'
    case 'ADEO_SubDepartment:1635': return '35 - FURNITURE AND INTERIOR DECORATIVE OBJECTS'
    case 'ADEO_SubDepartment:1640': return '40 - MISCELLANEOUS PRODUCTS'
    case 'ADEO_SubDepartment:1670': return '70 - PET CARE'
    case 'ADEO_SubDepartment:1699': return '99 - OTHER PRODUCTS: 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    case 'ADEO_SubDepartment:1715': return '15 - KITCHEN FAUCETS'
    case 'ADEO_SubDepartment:1745': return '45 - KITCHEN FURNITURE AND OTHER ITEMS'
    case 'ADEO_SubDepartment:1750': return '50 - WORKTOPS AND SPLASHBACKS'
    case 'ADEO_SubDepartment:1755': return '55 - KITCHEN SINKS AND WASHTUBS'
    case 'ADEO_SubDepartment:1760': return '60 - KITCHEN APPLIANCES'
    case 'ADEO_SubDepartment:1765': return '65 - KITCHEN FITTINGS AND ACCESSORIES'
    case 'ADEO_SubDepartment:1799': return '99 - KITCHEN : 48 CODES, UNALLOCATED AND MISCELLANEOUS'
    default: return null
  }
}
